config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end
  devise_for :users
  root to: 'categories#index'

  resources :users do
    resources :categories do
      resources :operations
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    return unless user.present?

    can :manage, Category, user_id: user.id
    can :manage, Operation, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
require 'uri'

class Category < ApplicationRecord
  belongs_to :user
  has_many :operations, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true, format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp}\z/,
                                             message: 'only allows valid URL of images including https//' }
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :operations, dependent: :destroy

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:full_name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @user = current_user
    @categories = @user.categories
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @user = User.find(params[:user_id])
    @category = @user.categories.new(category_params)
    if @category.save
      flash[:notice] = 'The category was added successfully'
      redirect_to user_category_path(user_id: params[:user_id], id: @category.id)
    else
      flash[:alert] = "Couldn't create the category!"
      render :new, status: :unprocessable_entity
    end
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  load_and_authorize_resource

  def new
    @category = Category.find(params[:category_id])
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.user_id = params[:user_id]
    if @operation.save
      flash.notice = 'The operation was registered successfully'
      redirect_to user_category_path(user_id: params[:user_id], id: @operation.category_id)
    else
      flash.alert = "The operation wasn\'t registered. Try again"
      render :new, status: :unprocessable_entity
    end
  end

  def operation_params
    params.require(:operation).permit(:name, :amount, :category_id)
  end
end

app/controllers/turbo_devise_controller.rb
# app/controllers/turbo_devise_controller.rb

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="flex justify-around w-full mx-auto px-5 py-3 text-sm font-medium text-white bg-[#3778c2]">
  <h1 class="text-3xl font-bold">Categories</h1>
  <%=  link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "ml-auto px-5 py-3 text-sm font-medium text-white bg-blue-600 rounded-lg" %>
</div>
<div class="flex flex-col gap-1">
  <% @categories.each do |category| %>
    <%= link_to user_category_path(user_id: category.user_id, id: category.id), class: "m-5 my-category" do%>
      <div class="flex gap-5 p-8 border border-gray-200 shadow-sm rounded-xl">
        <%= image_tag category.icon, class: "h-16 w-16 my-icon" %>
        <h2 class="flex-1 mt-4 text-lg font-medium text-gray-900"><%= category.name %></h2>
        <% sum = 0 %>
        <% category.operations.each do |operation|%>
          <% sum += operation.amount %>
        <% end %>
        <p class="flex-1 mt-4 text-md font-medium text-gray-900">Total: $<%= sum %></p>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to 'Create New Category', new_user_category_path(user_id: @user.id), class: "block w-11/12 mx-auto my-5 px-5 py-3 text-sm font-medium text-white bg-[#5fb523] rounded-lg" %>

app/views/categories/new.html.erb
<div class="flex justify-between gap-5 w-full px-5 py-3 text-sm font-medium text-white bg-[#3778c2]">
  <%= link_to root_path, class: "flex items-center" do %>
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
    </svg>
  <% end%>
</div>
<div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
  <div class="max-w-lg mx-auto">
    <h1 class="text-2xl font-bold text-center text-[#3778c2] sm:text-3xl">Add a new Category</h1>
    <%= form_with model: @category, url: user_categories_path, class: "mt-8 space-y-6" do |form| %>
      <div>
        <%= form.label :name, class: "text-sm font-medium" %><br>
        <%= form.text_field :name, class: "w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm" %>
        <% @category.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.label :icon, class: "text-sm font-medium" %><br>
        <%= form.text_area :icon, class: "w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm" %><br>
        <% @category.errors.full_messages_for(:icon).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.submit 'Create Category', class: "block w-full px-5 py-3 my-5 text-sm font-medium text-white bg-[#5fb523] rounded-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="flex justify-between gap-5 w-full px-5 py-3 text-sm font-medium text-white bg-[#3778c2]">
  <%= link_to user_categories_path(user_id: @category.user_id), class: "flex items-center" do %>
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
    </svg>
  <% end%>
  <div class="flex gap-1 items-center">
    <%= image_tag @category.icon, class: "h-8 w-8" %>
    <h1>Category: <%= @category.name %></h1>
  </div>
</div>
<div class="flex flex-col gap-4 p-4 bg-slate-200">
  <% @category.operations.each do |operation|%>
    <div class="flex justify-between p-4 bg-white border-gray-300 rounded-lg my-operation">
      <p><%= operation.name%></p>
      <p>Amount: $ <%= operation.amount %></p>
    </div>
  <% end %>
</div>
<%= link_to 'Add new operation', new_user_category_operation_path(user_id: params[:user_id], category_id: params[:id]), class: "block w-11/12 mx-auto px-5 py-3 text-sm font-medium text-white bg-[#5fb523] rounded-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <% if type == 'notice' %>
        <div class="p-4 text-green-700 border rounded border-green-900/10 bg-green-50" role="alert">
          <%= msg %>
        </div>
      <% else%>
        <div class="p-4 text-red-700 border rounded border-red-900/10 bg-red-50" role="alert">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/operations/new.html.erb
<div class="flex justify-between gap-5 w-full px-5 py-3 text-sm font-medium text-white bg-[#3778c2]">
  <%= link_to user_category_path(user_id: params[:user_id],id: params[:category_id]), class: "flex items-center" do %>
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
    </svg>
  <% end%>
</div>
<div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
  <div class="max-w-lg mx-auto">
    <h1 class="text-2xl font-bold text-center text-[#3778c2] sm:text-3xl">Add a new Operation</h1>
    <%= form_with model: @operation, url: user_category_operations_path, class: "mt-8 space-y-6", class: "p-8 mt-6 mb-0 space-y-4 rounded-lg shadow-2xl"  do |form|%>
      <div>
        <%= form.label :name, class: "text-sm font-medium" %><br>
        <%= form.text_field :name, class: "w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm" %>
        <% @operation.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.label :amount, class: "text-sm font-medium" %><br>
        <%= form.number_field :amount, step: :any, class: "w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm" %><br>
        <% @operation.errors.full_messages_for(:amount).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.label :category_id, class: "text-sm font-medium" %><br>
        <%= form.collection_select :category_id, Category.where(user_id: current_user.id), :id, :name, class: "w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm" %>
      </div>
      <div>
        <%= form.submit 'Create Operation', class: "block w-full px-5 py-3 my-5 text-sm font-medium text-white bg-[#5fb523] rounded-lg" %>
      </div>
    <% end %>
  </div>
</div>